In [1]:
import importlib
import New_data_prep as dp

importlib.reload(dp)

In [2]:
VERSION = 'V1'
base_output_folder = "../experiments"
path_to_csvs = "../data/raw/source_domain/"
path_to_csvs_target = "../data/raw/target_domain/"
path_to_networks = "../data/networks"
n = 11
k = 8
seed = 4850
split_seed=42
PATH_TO_SPLITS =  f"../data/splits/{VERSION}/"
PATH_TO_SCALERS =  f'../output/scalers/baselines/{VERSION}/'
node_types = ["LIGHT", "MID", "HEAVY"]

In [ ]:
#PATH_TO_AUGMENTED_ROWS = f"../data/augmented_rows/{VERSION}/"

In [3]:
simulation = 0

In [4]:
dp.prepare_data(
    base_output_folder,
    path_to_csvs,
    path_to_csvs_target,
    path_to_networks,
    PATH_TO_SPLITS,
    PATH_TO_SCALERS,
    n,
    k,
    seed,
    simulation,
    node_types,
    split_seed
)

/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/src/New_data_prep.py:59: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, *dataframes], axis=0, ignore_index=True)
/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/src/New_data_prep.py:70: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X.loc[:, col] = X.loc[:, col].fillna(0)

cpu_usage_function_shasum
23887
ram_usage_function_shasum
23430
medium_latency_function_shasum
23610
cpu_usage_function_curl
14017
ram_usage_function_curl
13650
medium_latency_function_curl
13920
cpu_usage_function_eat_memory
4571
ram_usage_function_eat_memory
4501
medium_latency_function_eat_memory
4564
cpu_usage_node
32741
ram_usage_node
32385
ram_usage_node_percentage
32127
ram_usage_node_perc_theor
32385
overloaded_node
overloaded_node
0.0    89169
1.0     9563
Name: count, dtype: int64
cpu_usage_function_nmap
7319
ram_usage_function_nmap
7245
medium_latency_function_nmap
7301
cpu_usage_function_env
19397
ram_usage_function_env
18812
medium_latency_function_env
19202
cpu_usage_function_figlet
19900
ram_usage_function_figlet
19762
medium_latency_function_figlet
19790
cpu_usage_function_figlet
16476
ram_usage_function_figlet
16403
medium_latency_function_figlet
16250
cpu_usage_function_shasum
16498
ram_usage_function_shasum
16352
medium_latency_function_shasum
16298
cpu_usage_function_nmap
7290
ram_usage_function_nmap
7192
medium_latency_function_nmap
7256
cpu_usage_node
21955
ram_usage_node
21629
ram_usage_node_percentage
22094
ram_usage_node_perc_theor
21629
overloaded_node
overloaded_node
0    59483
1     8090
Name: count, dtype: int64
cpu_usage_function_env
8297
ram_usage_function_env
8251
medium_latency_function_env
8119
cpu_usage_function_eat_memory
2817
ram_usage_function_eat_memory
2748
medium_latency_function_eat_memory
2756
cpu_usage_function_curl
6781
ram_usage_function_curl
6695
medium_latency_function_curl
6667
load nodes network
...done
build nodes dataframes
...done
split and save
processing node 0

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-05-12 20:22:36.510006
Start Train/Val Split: 2026-05-12 20:22:36.642588
Start Oversampling: 2026-05-12 20:22:36.728825

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 3120
After limiting: 1014 (removed 2106)

Class distribution after limiting:
overloaded_node
0.0                936
1.0                 78
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 0] Overloaded: 78, Non-overloaded: 936
Generating 858 synthetic samples for node_type 0
Generated 858 samples for node_type 0

 Total synthetic samples generated: 858
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(0)]


--- Processing node_type: 0 ---
Original counts → overloaded=0: 2886, overloaded=1: 234
Need to add 2652 more rows for overloaded=1
Augmented rows available for this node_type=0: 858
Repeating augmented rows 4 times
Rows actually added: 2652
After augmentation → overloaded=0: 2886, overloaded=1: 2886

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                2886
1.0                2886
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
0                2886  2886

Final node_type distribution:
node_type
0    5772
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 1872
Unique feature combinations for 0       : 936
Unique feature combinations for 1       : 936
==========================================

Start Preprocessing: 2026-05-12 20:22:36.776329

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
0          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows         5772        780         975

## Data Leakage Check:

Train Samples: 5772
Val Samples: 780
Test Samples: 975


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (5772, 7)
  - Regression targets shape: (5772, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (5772, 7)
  - X_val shape: (780, 7)
  - X_test shape: (975, 7)

Transforming for Janoosy: 2026-05-12 20:22:36.809541
processing node 4

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-05-12 20:22:37.520450
Start Train/Val Split: 2026-05-12 20:22:37.656227
Start Oversampling: 2026-05-12 20:22:37.743287

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 3196
After limiting: 1013 (removed 2183)

Class distribution after limiting:
overloaded_node
0.0                934
1.0                 79
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 0] Overloaded: 79, Non-overloaded: 934
Generating 855 synthetic samples for node_type 0
Generated 855 samples for node_type 0

 Total synthetic samples generated: 855
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(0)]


--- Processing node_type: 0 ---
Original counts → overloaded=0: 2959, overloaded=1: 237
Need to add 2722 more rows for overloaded=1
Augmented rows available for this node_type=0: 855
Repeating augmented rows 4 times
Rows actually added: 2722
After augmentation → overloaded=0: 2959, overloaded=1: 2959

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                2959
1.0                2959
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
0                2959  2959

Final node_type distribution:
node_type
0    5918
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 1868
Unique feature combinations for 0       : 934
Unique feature combinations for 1       : 934
==========================================

Start Preprocessing: 2026-05-12 20:22:37.788818

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
0          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows         5918        813        1011

## Data Leakage Check:

Train Samples: 5918
Val Samples: 813
Test Samples: 1011


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (5918, 7)
  - Regression targets shape: (5918, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (5918, 7)
  - X_val shape: (813, 7)
  - X_test shape: (1011, 7)

Transforming for Janoosy: 2026-05-12 20:22:37.839317
processing node 8

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-05-12 20:22:38.553706
Start Train/Val Split: 2026-05-12 20:22:38.687326
Start Oversampling: 2026-05-12 20:22:38.775081

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 3047
After limiting: 1013 (removed 2034)

Class distribution after limiting:
overloaded_node
0.0                933
1.0                 80
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 0] Overloaded: 80, Non-overloaded: 933
Generating 853 synthetic samples for node_type 0
Generated 853 samples for node_type 0

 Total synthetic samples generated: 853
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(0)]


--- Processing node_type: 0 ---
Original counts → overloaded=0: 2807, overloaded=1: 240
Need to add 2567 more rows for overloaded=1
Augmented rows available for this node_type=0: 853
Repeating augmented rows 4 times
Rows actually added: 2567
After augmentation → overloaded=0: 2807, overloaded=1: 2807

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                2807
1.0                2807
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
0                2807  2807

Final node_type distribution:
node_type
0    5614
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 1866
Unique feature combinations for 0       : 933
Unique feature combinations for 1       : 933
==========================================

Start Preprocessing: 2026-05-12 20:22:38.818391

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
0          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows         5614        762         955

## Data Leakage Check:

Train Samples: 5614
Val Samples: 762
Test Samples: 955


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (5614, 7)
  - Regression targets shape: (5614, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (5614, 7)
  - X_val shape: (762, 7)
  - X_test shape: (955, 7)

Transforming for Janoosy: 2026-05-12 20:22:38.848811
processing node 10

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-05-12 20:22:39.525633
Start Train/Val Split: 2026-05-12 20:22:39.659378
Start Oversampling: 2026-05-12 20:22:39.746465

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 3039
After limiting: 1013 (removed 2026)

Class distribution after limiting:
overloaded_node
0.0                936
1.0                 77
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 0] Overloaded: 77, Non-overloaded: 936
Generating 859 synthetic samples for node_type 0
Generated 859 samples for node_type 0

 Total synthetic samples generated: 859
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(0)]


--- Processing node_type: 0 ---
Original counts → overloaded=0: 2808, overloaded=1: 231
Need to add 2577 more rows for overloaded=1
Augmented rows available for this node_type=0: 859
Repeating augmented rows 3 times
Rows actually added: 2577
After augmentation → overloaded=0: 2808, overloaded=1: 2808

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                2808
1.0                2808
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
0                2808  2808

Final node_type distribution:
node_type
0    5616
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 1872
Unique feature combinations for 0       : 936
Unique feature combinations for 1       : 936
==========================================

Start Preprocessing: 2026-05-12 20:22:39.789987

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
0          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows         5616        762         951

## Data Leakage Check:

Train Samples: 5616
Val Samples: 762
Test Samples: 951


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (5616, 7)
  - Regression targets shape: (5616, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (5616, 7)
  - X_val shape: (762, 7)
  - X_test shape: (951, 7)

Transforming for Janoosy: 2026-05-12 20:22:39.820735
processing node 2

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-05-12 20:22:40.498074
Start Train/Val Split: 2026-05-12 20:22:40.784124
Start Oversampling: 2026-05-12 20:22:40.901087

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 6442
After limiting: 1938 (removed 4504)

Class distribution after limiting:
overloaded_node
0.0                1832
1.0                 106
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 1] Overloaded: 106, Non-overloaded: 1832
Generating 1726 synthetic samples for node_type 1
Generated 1726 samples for node_type 1

 Total synthetic samples generated: 1726
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(1)]


--- Processing node_type: 1 ---
Original counts → overloaded=0: 6092, overloaded=1: 350
Need to add 5742 more rows for overloaded=1
Augmented rows available for this node_type=1: 1726
Repeating augmented rows 4 times
Rows actually added: 5742
After augmentation → overloaded=0: 6092, overloaded=1: 6092

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                6092
1.0                6092
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
1                6092  6092

Final node_type distribution:
node_type
1    12184
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 3664
Unique feature combinations for 0       : 1832
Unique feature combinations for 1       : 1832
==========================================

Start Preprocessing: 2026-05-12 20:22:40.978864

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
1          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        12184       1563        2016

## Data Leakage Check:

Train Samples: 12184
Val Samples: 1563
Test Samples: 2016


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (12184, 7)
  - Regression targets shape: (12184, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (12184, 7)
  - X_val shape: (1563, 7)
  - X_test shape: (2016, 7)

Transforming for Janoosy: 2026-05-12 20:22:41.032131
processing node 3

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-05-12 20:22:42.488908
Start Train/Val Split: 2026-05-12 20:22:42.754313
Start Oversampling: 2026-05-12 20:22:42.867937

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 6267
After limiting: 1939 (removed 4328)

Class distribution after limiting:
overloaded_node
0.0                1833
1.0                 106
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 1] Overloaded: 106, Non-overloaded: 1833
Generating 1727 synthetic samples for node_type 1
Generated 1727 samples for node_type 1

 Total synthetic samples generated: 1727
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(1)]


--- Processing node_type: 1 ---
Original counts → overloaded=0: 5949, overloaded=1: 318
Need to add 5631 more rows for overloaded=1
Augmented rows available for this node_type=1: 1727
Repeating augmented rows 4 times
Rows actually added: 5631
After augmentation → overloaded=0: 5949, overloaded=1: 5949

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                5949
1.0                5949
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
1                5949  5949

Final node_type distribution:
node_type
1    11898
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 3666
Unique feature combinations for 0       : 1833
Unique feature combinations for 1       : 1833
==========================================

Start Preprocessing: 2026-05-12 20:22:42.942605

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
1          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        11898       1548        1950

## Data Leakage Check:

Train Samples: 11898
Val Samples: 1548
Test Samples: 1950


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (11898, 7)
  - Regression targets shape: (11898, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (11898, 7)
  - X_val shape: (1548, 7)
  - X_test shape: (1950, 7)

Transforming for Janoosy: 2026-05-12 20:22:42.995738
processing node 5

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-05-12 20:22:44.437237
Start Train/Val Split: 2026-05-12 20:22:44.695858
Start Oversampling: 2026-05-12 20:22:44.812082

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 6201
After limiting: 1938 (removed 4263)

Class distribution after limiting:
overloaded_node
0.0                1833
1.0                 105
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 1] Overloaded: 105, Non-overloaded: 1833
Generating 1728 synthetic samples for node_type 1
Generated 1728 samples for node_type 1

 Total synthetic samples generated: 1728
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(1)]


--- Processing node_type: 1 ---
Original counts → overloaded=0: 5886, overloaded=1: 315
Need to add 5571 more rows for overloaded=1
Augmented rows available for this node_type=1: 1728
Repeating augmented rows 4 times
Rows actually added: 5571
After augmentation → overloaded=0: 5886, overloaded=1: 5886

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                5886
1.0                5886
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
1                5886  5886

Final node_type distribution:
node_type
1    11772
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 3666
Unique feature combinations for 0       : 1833
Unique feature combinations for 1       : 1833
==========================================

Start Preprocessing: 2026-05-12 20:22:44.888812

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
1          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        11772       1546        1947

## Data Leakage Check:

Train Samples: 11772
Val Samples: 1546
Test Samples: 1947


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (11772, 7)
  - Regression targets shape: (11772, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (11772, 7)
  - X_val shape: (1546, 7)
  - X_test shape: (1947, 7)

Transforming for Janoosy: 2026-05-12 20:22:44.942639
processing node 6

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-05-12 20:22:46.368920
Start Train/Val Split: 2026-05-12 20:22:46.628250
Start Oversampling: 2026-05-12 20:22:46.747998

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 5945
After limiting: 1938 (removed 4007)

Class distribution after limiting:
overloaded_node
0.0                1832
1.0                 106
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 1] Overloaded: 106, Non-overloaded: 1832
Generating 1726 synthetic samples for node_type 1
Generated 1726 samples for node_type 1

 Total synthetic samples generated: 1726
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(1)]


--- Processing node_type: 1 ---
Original counts → overloaded=0: 5629, overloaded=1: 316
Need to add 5313 more rows for overloaded=1
Augmented rows available for this node_type=1: 1726
Repeating augmented rows 4 times
Rows actually added: 5313
After augmentation → overloaded=0: 5629, overloaded=1: 5629

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                5629
1.0                5629
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
1                5629  5629

Final node_type distribution:
node_type
1    11258
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 3664
Unique feature combinations for 0       : 1832
Unique feature combinations for 1       : 1832
==========================================

Start Preprocessing: 2026-05-12 20:22:46.821344

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
1          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        11258       1479        1857

## Data Leakage Check:

Train Samples: 11258
Val Samples: 1479
Test Samples: 1857


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (11258, 7)
  - Regression targets shape: (11258, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (11258, 7)
  - X_val shape: (1479, 7)
  - X_test shape: (1857, 7)

Transforming for Janoosy: 2026-05-12 20:22:46.894873
processing node 7

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-05-12 20:22:48.262417
Start Train/Val Split: 2026-05-12 20:22:48.523128
Start Oversampling: 2026-05-12 20:22:48.637417

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 5813
After limiting: 1938 (removed 3875)

Class distribution after limiting:
overloaded_node
0.0                1833
1.0                 105
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 1] Overloaded: 105, Non-overloaded: 1833
Generating 1728 synthetic samples for node_type 1
Generated 1728 samples for node_type 1

 Total synthetic samples generated: 1728
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(1)]


--- Processing node_type: 1 ---
Original counts → overloaded=0: 5498, overloaded=1: 315
Need to add 5183 more rows for overloaded=1
Augmented rows available for this node_type=1: 1728
Repeating augmented rows 3 times
Rows actually added: 5183
After augmentation → overloaded=0: 5498, overloaded=1: 5498

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                5498
1.0                5498
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
1                5498  5498

Final node_type distribution:
node_type
1    10996
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 3666
Unique feature combinations for 0       : 1833
Unique feature combinations for 1       : 1833
==========================================

Start Preprocessing: 2026-05-12 20:22:48.712289

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
1          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        10996       1453        1817

## Data Leakage Check:

Train Samples: 10996
Val Samples: 1453
Test Samples: 1817


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (10996, 7)
  - Regression targets shape: (10996, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (10996, 7)
  - X_val shape: (1453, 7)
  - X_test shape: (1817, 7)

Transforming for Janoosy: 2026-05-12 20:22:48.762066
processing node 9

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-05-12 20:22:50.078665
Start Train/Val Split: 2026-05-12 20:22:50.362308
Start Oversampling: 2026-05-12 20:22:50.476294

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 5832
After limiting: 1939 (removed 3893)

Class distribution after limiting:
overloaded_node
0.0                1833
1.0                 106
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 1] Overloaded: 106, Non-overloaded: 1833
Generating 1727 synthetic samples for node_type 1
Generated 1727 samples for node_type 1

 Total synthetic samples generated: 1727
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(1)]


--- Processing node_type: 1 ---
Original counts → overloaded=0: 5514, overloaded=1: 318
Need to add 5196 more rows for overloaded=1
Augmented rows available for this node_type=1: 1727
Repeating augmented rows 4 times
Rows actually added: 5196
After augmentation → overloaded=0: 5514, overloaded=1: 5514

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                5514
1.0                5514
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
1                5514  5514

Final node_type distribution:
node_type
1    11028
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 3666
Unique feature combinations for 0       : 1833
Unique feature combinations for 1       : 1833
==========================================

Start Preprocessing: 2026-05-12 20:22:50.549656

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
1          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        11028       1467        1821

## Data Leakage Check:

Train Samples: 11028
Val Samples: 1467
Test Samples: 1821


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (11028, 7)
  - Regression targets shape: (11028, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (11028, 7)
  - X_val shape: (1467, 7)
  - X_test shape: (1821, 7)

Transforming for Janoosy: 2026-05-12 20:22:50.599644
processing node 1

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-05-12 20:22:51.914135
Start Train/Val Split: 2026-05-12 20:22:52.443464
Start Oversampling: 2026-05-12 20:22:52.615930

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 14321
After limiting: 3914 (removed 10407)

Class distribution after limiting:
overloaded_node
0.0                2917
1.0                 997
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 2] Overloaded: 997, Non-overloaded: 2917
Generating 1920 synthetic samples for node_type 2
Generated 1920 samples for node_type 2

 Total synthetic samples generated: 1920
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(2)]


--- Processing node_type: 2 ---
Original counts → overloaded=0: 11081, overloaded=1: 3240
Need to add 7841 more rows for overloaded=1
Augmented rows available for this node_type=2: 1920
Repeating augmented rows 5 times
Rows actually added: 7841
After augmentation → overloaded=0: 11081, overloaded=1: 11081

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                11081
1.0                11081
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node    0.0    1.0
node_type
2                11081  11081

Final node_type distribution:
node_type
2    22162
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 5834
Unique feature combinations for 0       : 2917
Unique feature combinations for 1       : 2917
==========================================

Start Preprocessing: 2026-05-12 20:22:52.757274

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
2          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        22162       3568        4435

## Data Leakage Check:

Train Samples: 22162
Val Samples: 3568
Test Samples: 4435


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (22162, 7)
  - Regression targets shape: (22162, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (22162, 7)
  - X_val shape: (3568, 7)
  - X_test shape: (4435, 7)

Transforming for Janoosy: 2026-05-12 20:22:52.846927
...done

'../experiments/11n-8k/seed4850/0'

# testing

In [78]:
import pandas as pd

In [79]:
df_augmentation=pd.read_csv('/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/data/augmented_rows/V1/augmented_overloaded_samples.csv')

In [80]:
df_augmentation.duplicated().sum()

np.int64(0)

In [81]:
df_augmentation[df_augmentation.duplicated()]

Empty DataFrame
Columns: [rate_function_curl, rate_function_eat_memory, rate_function_env, rate_function_figlet, rate_function_nmap, rate_function_shasum, node_type, overloaded_node, cpu_usage_node, ram_usage_node, ram_usage_node_percentage]
Index: []

In [82]:
df_augmentation.count()

rate_function_curl           1911
rate_function_eat_memory     1911
rate_function_env            1911
rate_function_figlet         1911
rate_function_nmap           1911
rate_function_shasum         1911
node_type                    1911
overloaded_node              1911
cpu_usage_node               1911
ram_usage_node               1911
ram_usage_node_percentage    1911
dtype: int64

In [83]:
import json

path = "/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/experiments/9n-8k/seed4850/0/8_data.json"

with open(path, "r") as f:
    data = json.load(f)

In [84]:
print(data.keys())

dict_keys(['X_train', 'Y_train', 'X_val', 'Y_val', 'X_test', 'Y_test'])

In [96]:
Y_train= data["Y_train"]

In [97]:
import numpy as np

Y_train = np.array(Y_train)

In [98]:
Y_flat = Y_train.reshape(Y_train.shape[0], -1)
df_Y = pd.DataFrame(Y_flat)

In [100]:
df_Y

             0         1         2    3
0     1.565072  1.235852  1.224230  0.0
1     1.515785  1.247027  1.229086  0.0
2     1.540481  1.243401  1.226580  0.0
3     1.583645  1.239013  1.220261  0.0
4     1.562825  1.229713  1.213577  0.0
...        ...       ...       ...  ...
2487  1.538328  1.564165  1.688982  1.0
2488  1.538328  1.564165  1.688982  1.0
2489  1.538328  1.564165  1.688982  1.0
2490  1.538328  1.564165  1.688982  1.0
2491  1.806737  1.764103  1.815300  1.0

[2492 rows x 4 columns]

In [85]:
X_train = data["X_train"]

In [86]:
X_train

[[[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.4500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.100000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.4500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.100000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.2000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.4500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.5, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.7999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.100000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.100000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.4500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.100000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.4500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],

In [87]:
import numpy as np

X_train = np.array(X_train)

In [88]:
X_flat = X_train.reshape(X_train.shape[0], -1)
df = pd.DataFrame(X_flat)

In [89]:
df

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1.60,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.250000,0.0,...,0.0,0.0,1.800,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.65,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.250000,0.0,...,0.0,0.0,1.800,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.70,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.250000,0.0,...,0.0,0.0,1.800,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.75,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.250000,0.0,...,0.0,0.0,1.800,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.80,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.250000,0.0,...,0.0,0.0,1.800,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2487,1.60,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.897436,0.0,...,0.0,0.0,1.950,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2488,1.60,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.948718,0.0,...,0.0,0.0,1.950,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2489,1.60,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.000000,0.0,...,0.0,0.0,1.950,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2490,1.60,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.102564,0.0,...,0.0,0.0,1.975,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2491,1.65,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.179487,0.0,...,0.0,0.0,1.950,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [90]:
df.duplicated().sum()

np.int64(0)

In [91]:
df.count()

0     2492
1     2492
2     2492
3     2492
4     2492
5     2492
6     2492
7     2492
8     2492
9     2492
10    2492
11    2492
12    2492
13    2492
14    2492
15    2492
16    2492
17    2492
18    2492
19    2492
20    2492
21    2492
22    2492
23    2492
dtype: int64

In [92]:
len(df.drop_duplicates())

2492

In [93]:
df[df.duplicated()]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Index: []

[0 rows x 24 columns]

In [94]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Index: []

[0 rows x 24 columns]

In [95]:
df.value_counts()[df.value_counts() > 2]

Series([], Name: count, dtype: int64)